# basic details
title: Cubie's Site
author:
  name: Cubie
#  email: "testemailhere"
github_username: cubie87

# theme
theme: minima


# header pages
header_pages:
  - index.md


# plugins for the theme
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings # remove double titles on pages
  - jekyll-last-modified-at


last_modified_at:
  date_format: "%b %-d, %Y"
  time_format: "%I:%M %p"



# remove double titles on pages
titles_from_headings:
  enabled: true
  strip_title: true
  collections: false

minima:
  skin: dark # dark mode
  social_links: # social medias
    - { platform: github,  user_url: "https://github.com/Cubie87" }
