# theme
remote_theme: kitian616/jekyll-TeXt-theme

text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"


# basic details
title: Cubie's Site
description: > # this means to ignore newlines until "Language & timezone"
  Home to mindless ramblings and interesting notes.
author:
  name: Cubie
#  email: "testemailhere"


paths:
  root    : # title link url, "/" (default)
  #home    : # home layout url, "/" (default)


repository: Cubie87/cubie87.github.io
repository_tree: master


# Maths 
mathjax: # false (default), true
