# basic details
#title: 
#email: 
#description:
#github_username: 
#linkedin_username: 
#stackoverflow_username: 
author: Cubie

# theme
remote_theme: jekyll/minima


# header pages
header_pages:
  - index.md


# plugins for the theme
plugins:
  - jekyll-remote-theme # dark mode theme
  - jekyll-titles-from-headings # remove double titles on pages


# dark mode skin
minima:
  skin: dark


# remove double titles on pages
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
