# basic details
title: Cubie's Site
author:
  name: Cubie
#  email: "testemailhere"
github_username: cubie87

# theme
remote_theme: jekyll/minima


# header pages
header_pages:
  - index.md


# plugins for the theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme # required for remote_theme definition
  - jekyll-titles-from-headings # remove double titles on pages


# remove double titles on pages
titles_from_headings:
  enabled: true
  strip_title: true
  collections: false

minima:
  skin: dark # dark mode
  social_links: # social medias
    - { platform: github,  user_url: "https://github.com/Cubie87" }
  stylesheet: "/assets/main.scss"  # Add this line



defaults:
  -
    scope:
      path: ""
    values:
      include:
        - "_includes"
