# basic details
title: Cubie's Site
author:
  name: Cubie
#  email: "testemailhere"
  
  
github_username: cubie87
#linkedin_username: 
#stackoverflow_username:

# theme
remote_theme: abhinavs/moonwalk


# header pages
header_pages:
  - index.md

